QuantHockeyMap = {
    "players": {
        "headerRow": 1,
        "indexCol": 0,
        "columns": {
            "Rk":{"Name":"Index"},
            "Name":{"Name":"Name"},
            "Team":{"Name":"Team"},
            "Age":{"Name":"Age"},
            "Pos":{"Name":"Pos"},
            "GP":{"Name":"GP"},
            "G":{"Name":"G", "Weight": 3},
            "A":{"Name":"A", "Weight": 1.5},
            "P":{"Name":"P"},
            "PIM":{"Name":"PIM"},
            "+/-":{"Name":"PlusMin", "Weight": 1},
            "TOI":{"Name":"TOI"},
            "ES":{"Name":"ESTOI"},
            "PP":{"Name":"PPTOI"},
            "SH":{"Name":"SHTOI"},
            "ESG":{"Name":"ESG"},
            "PPG":{"Name":"PPG"},
            "SHG":{"Name":"SHG", "Weight": 2},
            "GWG":{"Name":"GWG", "Weight": 2},
            "OTG":{"Name":"OTG"},
            "ESA":{"Name":"ESA"},
            "PPA":{"Name":"PPA"},
            "SHA":{"Name":"SHA"},
            "GWA":{"Name":"GWA"},
            "OTA":{"Name":"OTA"},
            "ESP":{"Name":"ESP"},
            "PPP":{"Name":"PPP", "Weight": 1},
            "SHP":{"Name":"SHP"},
            "GWP":{"Name":"GWP"},
            "OTP":{"Name":"OTP"},
            "PPP%":{"Name":"PPPPercent"},
            "G/60":{"Name":"GPer60"},
            "A/60":{"Name":"APer60"},
            "P/60":{"Name":"PPer60"},
            "ESG/60":{"Name":"ESGPer60"},
            "ESA/60":{"Name":"ESAPer60"},
            "ESP/60":{"Name":"ESPPer60"},
            "PPG/60":{"Name":"PPGPer60"},
            "PPA/60":{"Name":"PPAPer60"},
            "PPP/60":{"Name":"PPPPer60"},
            "G/GP":{"Name":"GPerGP"},
            "A/GP":{"Name":"APerGP"},
            "P/GP":{"Name":"PPerGP"},
            "SHOTS":{"Name":"Shots", "Weight": 0.5},
            "SH%":{"Name":"ShotPercent"},
            "HITS":{"Name":"Hits", "Weight": 0.5},
            "BS":{"Name":"BS", "Weight": 0.2},
            "FOW":{"Name":"FOW"},
            "FOL":{"Name":"FOL"},
            "FO%":{"Name":"FOPercent"}
        }
    },
    "goalies":{
        "indexCol":0,
        "headerRow":0,
        "columns":{
            "Rk":{"Name":"Index"},
            "Name":{"Name":"Name"},
            "Age":{"Name": "Age"},
            "Team":{"Name": "Team"},
            "GP":{"Name": "GP", "Weight": 1},
            "GAA":{"Name": "GAA"},
            "SV%":{"Name": "SVPercent"},
            "W":{"Name": "W", "Weight": 1},
            "L":{"Name": "L"},
            "SO":{"Name": "SO", "Weight": 2},
            "TIME":{"Name": "TIME"},
            "G":{"Name": "G"},
            "A":{"Name": "A"},
            "P":{"Name": "P"},
            "PIM":{"Name": "PIM"}
        }
    }
}